### ISSUE TITLE
Images no longer have _00 or _01 suffix

### ISSUE THREAD

**Issue by BenJuan26** [DavidMarzocca/SpaceviewLive#1]
The script does not work in its current form because EPIC images no longer end in `_00` or `_01`. Removing that logic allows the script to succeed.

**Comment by DavidMarzocca** [comment]
Thanks so much! I had no time to check what was the issue so I stopped using the script last year. Now it works again, fantastic! I will update it on github.
Also, it is nice to see also other people were using it :) cheers!
